version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Berlin"
    labels:
      - "type: chore"
      - "type: dependency"
      - "priority: p2"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
