apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # Grafana accesses Prometheus on the server side
    url: http://prometheus:9090
    isDefault: true # default data source
    editable: true # you can edit this data source in the Grafana interface
